files:
  - source: freecad/asm3/translations/asm3.ts
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
    dest: /asm3.ts
    escape_quotes: 0
    escape_special_characters: 0
